apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-t4pa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-fyxp-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-t4pa@sha256:83cc7190340878ed0bedb1ec7f44e885f5e813a6841640aab8011a4a6dd3ea9b
        name: my-nodejs
        resources: {}
status: {}
